let weather = [
    {
        day: '16',
        month: '11',
        year: '2019',
        temperature: '30',
        status: 'Partly Cloudy',
    },
    {
        day: '17',
        month: '11',
        year: '2019',
        temperature: '31',
        status: 'Partly Cloudy',
    },
    {
        day: '18',
        month: '11',
        year: '2019',
        temperature: '25',
        status: 'Rain',
    },
    {
        day: '19',
        month: '11',
        year: '2019',
        temperature: '22',
        status: 'Partly Cloudy',
    },
    {
        day: '20',
        month: '11',
        year: '2019',
        temperature: '23',
        status: 'Partly Cloudy',
    },
    {
        day: '21',
        month: '11',
        year: '2019',
        temperature: '25',
        status: 'Sunnny',
    },
    {
        day: '22',
        month: '11',
        year: '2019',
        temperature: '26',
        status: 'Sunny',
    },
    {
        day: '23',
        month: '11',
        year: '2019',
        temperature: '27',
        status: 'Partly Cloudy',
    },
    {
        day: '24',
        month: '11',
        year: '2019',
        temperature: '27',
        status: 'Partly Cloudy',
    },
    {
        day: '25',
        month: '11',
        year: '2019',
        temperature: '26',
        status: 'Rain',
    },
    {
        day: '26',
        month: '11',
        year: '2019',
        temperature: '31',
        status: 'Partly Cloudy',
    },
]